#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

EXTENSION="js|mjs|ts|tsx"
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "(${EXTENSION})$" | tr '\n' ' ')

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

bun biome check --apply $STAGED_FILES

if git diff --cached --quiet; then
  echo "No changes left to commit. Aborting."
  exit 1
fi
